### ISSUE TITLE
Checkout for order payment does not work for all views

### ISSUE THREAD

**Issue by samuelhurni** [Twint-AG/twint-woocommerce-extension#2]
Hello 

When I do the checkout in my WooCommerce Shop by forwarding to the payment link directly, the Twint checkout is available but does not work at all, so not even the QR code is appearing, just a blank page. I tested it also with the other options like Kredit Card from WooPayment and this was working smoothly. So it looks to me that the plugin is running into an error. 

<img width="940" alt="image" src="https://github.com/user-attachments/assets/7939214a-de5a-4cb9-96e8-9650b7e42672">

In the screenshot you should see the site from where I do the payment. The URL to this site was in my configuration this one:
https://domainname.ch/kasse/order-pay/188/?pay_for_order=true&key=wc_order_vFrosOcO55BHG

I did some further investigations and activated the WordPress Debug function and found this in my debug.log file after clicking the button with Twint as payment method selected:

_```
wp-content/plugins/Archive/vendor/twint-ag/sdk/src/polyfill.php on line 17
[09-Nov-2024 03:44:20 UTC] PHP Warning:  Class "TwintWoo\Deprecated" not found in /home/samuel4/www/payment.mealorder.ch/wp-content/plugins/Archive/vendor/twint-ag/sdk/src/polyfill.php on line 27
[09-Nov-2024 03:44:21 UTC] PHP Warning:  Class "TwintWoo\SensitiveParameter" not found in /home/samuel4/www/payment.mealorder.ch/wp-content/plugins/Archive/vendor/twint-ag/sdk/src/polyfill.php on line 10
[09-Nov-2024 03:44:21 UTC] PHP Warning:  Class "TwintWoo\Override" not found in /home/samuel4/www/payment.mealorder.ch/wp-content/plugins/Archive/vendor/twint-ag/sdk/src/polyfill.php on line 17
[09-Nov-2024 03:44:21 UTC] PHP Warning:  Class "TwintWoo\Deprecated" not found in /home/samuel4/www/payment.mealorder.ch/wp-content/plugins/Archive/vendor/twint-ag/sdk/src/polyfill.php on line 27
[09-Nov-2024 03:44:21 UTC] PHP Notice:  Die Funktion wpdb::prepare wurde <strong>fehlerhaft</strong> aufgerufen. Nicht unterstützter ValueType (array). Weitere Informationen: <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress (engl.)</a>. (Diese Meldung wurde in Version 4.8.2 hinzugefügt.) in /home/samuel4/www/payment.mealorder.ch/wp-includes/functions.php on line 6085
[09-Nov-2024 03:44:22 UTC] PHP Warning:  Class "TwintWoo\SensitiveParameter" not found in /home/samuel4/www/payment.mealorder.ch/wp-content/plugins/Archive/vendor/twint-ag/sdk/src/polyfill.php on line 10
[09-Nov-2024 03:44:22 UTC] PHP Warning:  Class "TwintWoo\Override" not found in /home/samuel4/www/payment.mealorder.ch/wp-content/plugins/Archive/vendor/twint-ag/sdk/src/polyfill.php on line 17
[09-Nov-2024 03:44:22 UTC] PHP Warning:  Class "TwintWoo\Deprecated" not found in /home/samuel4/www/payment.mealorder.ch/wp-content/plugins/Archive/vendor/twint-ag/sdk/src/polyfill.php on line 27
[09-Nov-2024 03:44:22 UTC] PHP Warning:  Class "TwintWoo\SensitiveParameter" not found in /home/samuel4/www/payment.mealorder.ch/wp-content/plugins/Archive/vendor/twint-ag/sdk/src/polyfill.php on line 10
[09-Nov-2024 03:44:22 UTC] PHP Warning:  Class "TwintWoo\Override" not found in /home/samuel4/www/payment.mealorder.ch/wp-content/plugins/Archive/vendor/twint-ag/sdk/src/polyfill.php on line 17
[09-Nov-2024 03:44:22 UTC] PHP Warning:  Class "TwintWoo\Deprecated" not found in /home/samuel4/www/payment.mealorder.ch/wp-content/plugins/Archive/vendor/twint-ag/sdk/src/polyfill.php on line 27
[09-Nov-2024 03:44:25 UTC] PHP Warning:  Class "TwintWoo\SensitiveParameter" not found in /home/samuel4/www/payment.mealorder.ch/wp-content/plugins/Archive/vendor/twint-ag/sdk/src/polyfill.php on line 10
[09-Nov-2024 03:44:25 UTC] PHP Warning:  Class "TwintWoo\Override" not found in /home/samuel4/www/payment.mealorder.ch/wp-content/plugins/Archive/vendor/twint-ag/sdk/src/polyfill.php on line 17
[09-Nov-2024 03:44:25 UTC] PHP Warning:  Class "TwintWoo\Deprecated" not found in /home/samuel4/www/payment.mealorder.ch/wp-content/plugins/Archive/vendor/twint-ag/sdk/src/polyfill.php on line 27
[09-Nov-2024 03:44:35 UTC] PHP Warning:  Class "TwintWoo\SensitiveParameter" not found in /home/samuel4/www/payment.mealorder.ch/wp-content/plugins/Archive/vendor/twint-ag/sdk/src/polyfill.php on line 10
[09-Nov-2024 03:44:35 UTC] PHP Warning:  Class "TwintWoo\Override" not found in /home/samuel4/www/payment.mealorder.ch/wp-content/plugins/Archive/vendor/twint-ag/sdk/src/polyfill.php on line 17
```_

**Comment by samuelhurni** [comment]
Additional information to the given Issue tested with RC22 where the payment process still runs into an error:

Video Link from WeTransfer about the procedure and the debugger tools in Chrome: https://we.tl/t-r93nmsCmbC


Related Debug Log:
[19-Nov-2024 11:07:05 UTC] PHP Notice:  Die Funktion wpdb::prepare wurde <strong>fehlerhaft</strong> aufgerufen. Nicht unterstützter ValueType (array). Weitere Informationen: <a href=https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/>Debugging in WordPress (engl.)</a>. (Diese Meldung wurde in Version 4.8.2 hinzugefügt.) in /home/samuel4/www/payment.mealorder.ch/wp-includes/functions.php on line 6114


wpdb::prepare should be a function called from this plugin.

**Comment by krnfq** [comment]
Hi @samuelhurni can you please installed the latest version? The bugs should be fixed in the new releases. Thank you!

**Comment by samuelhurni** [comment]
Hi, @krnfq  with RC26 still the same behavior happened with a short spinner and a white blank page. The error in the debug.log file looks different. Here is the log file after clicking the button for the payment.



`PHP Notice:  Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>woocommerce-payments</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /home/samuel4/www/payment.mealorder.ch/wp-includes/functions.php on line 6114
[28-Nov-2024 21:15:00 UTC] PHP Notice:  Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>woocommerce</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /home/samuel4/www/payment.mealorder.ch/wp-includes/functions.php on line 6114
[28-Nov-2024 21:15:01 UTC] PHP Notice:  Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>woocommerce-payments</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /home/samuel4/www/payment.mealorder.ch/wp-includes/functions.php on line 6114
[28-Nov-2024 21:15:01 UTC] PHP Notice:  Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>woocommerce</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /home/samuel4/www/payment.mealorder.ch/wp-includes/functions.php on line 6114
[28-Nov-2024 21:15:01 UTC] PHP Notice:  Die Funktion wpdb::prepare wurde <strong>fehlerhaft</strong> aufgerufen. Nicht unterstützter ValueType (array). Weitere Informationen: <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress (engl.)</a>. (Diese Meldung wurde in Version 4.8.2 hinzugefügt.) in /home/samuel4/www/payment.mealorder.ch/wp-includes/functions.php on line 6114
[28-Nov-2024 21:15:02 UTC] PHP Notice:  Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>woocommerce-payments</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /home/samuel4/www/payment.mealorder.ch/wp-includes/functions.php on line 6114
[28-Nov-2024 21:15:02 UTC] PHP Notice:  Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>woocommerce</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /home/samuel4/www/payment.mealorder.ch/wp-includes/functions.php on line 6114
[28-Nov-2024 21:15:02 UTC] PHP Notice:  Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>woocommerce-payments</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /home/samuel4/www/payment.mealorder.ch/wp-includes/functions.php on line 6114
[28-Nov-2024 21:15:02 UTC] PHP Notice:  Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>woocommerce</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /home/samuel4/www/payment.mealorder.ch/wp-includes/functions.php on line 6114
[28-Nov-2024 21:15:08 UTC] PHP Notice:  Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>woocommerce-payments</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /home/samuel4/www/payment.mealorder.ch/wp-includes/functions.php on line 6114
[28-Nov-2024 21:15:08 UTC] PHP Notice:  Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>woocommerce</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /home/samuel4/www/payment.mealorder.ch/wp-includes/functions.php on line 6114`


Let me know if you need more information.

**Comment by krnfq** [comment]
Hi @samuelhurni 
We visited the site of yours: https://payment.mealorder.ch and can't seem to reproduce the same issue of yours. 
Would it be possible for you to also activate Express Checkout on your site for further testing? Thank you!

**Comment by samuelhurni** [comment]
Hi @krnfq  

I changed the site a little bit that you are able to reproduce it by yourself. you can now go to the following link:

https://payment.mealorder.ch/kasse/?guid=ABC123

and an order will created and you get to the payment view. I leave also the woopayment on with Credit Card in testmode. This is also working as it should to compare to the Twint option for you. For the Credit Card you have to use the test credentials as card number which are displayed in the same view.

The express checkout is right now now longer a option for me because as I have heard are just the ZKB and the UBS Twint App planned to get updated to support this function in the comming months / years.

**Comment by krnfq** [comment]
Hi @samuelhurni 
Thanks for your feedback! We did some investigation and made some changes. Can you please try 1.0.0-RC28 and let us know if the issue still exists? Thank you.

**Comment by samuelhurni** [comment]
Hi @krnfq 

I updated the plugin and now the payment can be done. Good work! One thing which for me is unclear if this is the normal case is when I do not press "Close" Button in the Twint App after I did the payment. 

![image](https://github.com/user-attachments/assets/cd39ea68-d3a2-4dfe-8726-f1e94e79de59)


When I return to the website afterwards it does not refresh/load automatically to go back to the Woocommerce part and stays just at the page where you have to select the Twint App you are using. Refreshing the page run into an error. I guess this could lead to a lot of failures when people forget doing this step.  This happens just if you are doing everything on your smartphone, like the order and the payment. If the order is on a separate device (Laptop) and the payment from the smartphone, this does not happen. But since orders per smartphone increase I guess this should also work there as expected?

Are you aware of this already or is this new to you?

**Comment by krnfq** [comment]
Hi @samuelhurni glad to hear the payment can be done now! 

Regarding your question: 
The “Close” button is not a must. 
When it’s not clicked, the waiting time is still necessary (the systems need to sync etc.) and user will be redirected to Order Details page. If user refreshes the page before the redirect, user will see a message box . WooCommerce handles all other necessary actions and refreshing or so won't affect the transaction with TWINT, since it is already confirmed (greenscreen in the App).

Hope this helps!

**Comment by samuelhurni** [comment]
@krnfq I have now the app in pilot phase and I get more and more the feedback, that sometimes the automatic forwarding when returning to the website is not done. The payment process was finished sucessfully. It happens random and I can not figure out what the issue is. I would say that 9 out of 10 times it is working but in this crucial step of the payment process of a customer, it iritates the customer because by refereshing the page manually an error from wooCommerce appears which says that a second payment is not possible because this one was already finished. But with this error I can not show the customer the summary page with his order number.

Can you please start investigating how this can happen?

**Comment by krnfq** [comment]
Hi @samuelhurni 
Thanks for raising this issue. We'll look into this issue and see try to reproduce. As this happens randomly, while we're investigating/reproducing the issue, it'd be great if you could capture some more details the next time you encounter this issue and share them:
1. The failed cases, what device and browser were in used? 
2. how 'long' did the user wait before they hit the refresh button? 

Thank you very much.

**Comment by samuelhurni** [comment]
Hi @krnfq 

It happened on IOS in Safari Browser. The user was waiting more than 10s so I assume the webhook was lost. I am not sure but this could be maybe because SignalR connections get closed when switching Apps or Lock the phone. 

Did you make any further improvements for newer versions of the plugin regarding this issue?

**Comment by krnfq** [comment]
Hi @samuelhurni 
Thanks for your feedback.
When the "Thank you" summary page is not shown, can you see the order in the Admin panel? Did you receive confirmation email?

**Comment by nhamtphat** [comment]
Hi there, please help try to install the latest version. We are always here to help if you have any questions. To keep our community tidy, please help us close resolved issues, and don't hesitate to open a new issue if you encounter another problem.

Thank you,
Phat
